### ISSUE TITLE
Needs audit

### ISSUE THREAD

**Issue by withoutboats** [dignifiedquire/pin-cell#3]
Someone else should check that the API I've implemented is actually safe.

cc @RalfJung @cramertj (context: this crate is a pin-safe version of RefCell that only gives you `Pin<&mut T>` pointers from interior mutability)

**Comment by cramertj** [comment]
This seems fine to me, but what is the purpose? It seems like we could add the same API to RefCell itself.

**Comment by withoutboats** [comment]
> This seems fine to me, but what is the purpose? It seems like we could add the same API to RefCell itself.

We can't, its only safe if the cell type does not have an API analogous to `RefCell::borrow_mut`, because `Pin<&RefCell<T>>` implements `Deref`. Pin projecting through a `RefCell` is not safe.

**Comment by cramertj** [comment]
Oh, of course-- thanks XD

**Comment by RalfJung** [comment]
I took a rather quick look over the API (its types, not its implementation) and it seems fine to me. You are handing out `&T` to the content that do no longer reflect that this is pinned, but one can get an `&T` from a `Pin<&T>` safely so that on its own cannot be a problem. We can have aliasing `&T` and `Pin<&T>` to the same thing at the same time and that, too, also follows from `Pin::deref`.

Crucially, one can NOT get an `&mut T` from an `&PinCell<T>`.

Some comments/questions:

* Why do you not have a `get_pin_mut(Pin<&mut PinCell<T>>) -> Pin<&mut T>` without run-time checks? Seems that should be fine, right?

* Here:

    https://github.com/withoutboats/pin-cell/blob/cd42d6d5ad19222c394aa513f073836cc069e756/src/lib.rs#L89-L91

    one condition is missing: The struct must also not be `packed`.

**Comment by withoutboats** [comment]
> Why do you not have a get_pin_mut(Pin<&mut PinCell<T>>) -> Pin<&mut T> without run-time checks? Seems that should be fine, right?

Oversight! This would be a good addition.
